name: Build Plugin
description: Build a habitable plugin
inputs:
  working-directory:
    description: The working directory of the plugin
    required: true
  os:
    description: Build operating system
    required: true
  arch:
    description: Build architecture
    required: true
runs:
  using: composite
  steps:
  - uses: actions/checkout@v2

  - name: Set up Go
    uses: actions/setup-go@v2
    with:
      go-version: 1.17.6

  - name: Build
    working-directory: ${{ inputs.working-directory }}
    run: go build -buildmode=plugin
    env:
      GOARCH: ${{ inputs.arch }}
      CGO_ENABLED: 1
    shell: bash

  - name: Create release dir
    run: mkdir -p /tmp/release
    shell: bash

  - name: Move to artifact
    working-directory: ${{ inputs.working-directory }}
    run: mv ${{ inputs.working-directory }}.so /tmp/release/${{ inputs.working-directory }}_${{ inputs.os }}_${{ inputs.arch }}.so
    shell: bash

  - name: Test
    working-directory: ${{ inputs.working-directory }}
    run: go test
    shell: bash

  - name: Release
    uses: softprops/action-gh-release@v0.1.14
    if: startsWith(github.ref, 'refs/tags/')
    with:
      files: /tmp/release/**/*
