name: Go

on:
  push:
    branches:
    - main
    tags:        
    - v**
  pull_request:
    branches:
    - main

jobs:

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
        - exec
        - http
        arch:
        - amd64
    steps:

    - uses: actions/checkout@v2

    - id: Build_Plugin
      uses: ./.github/actions/build-plugin
      with:
        working-directory: ${{ matrix.working-directory }}
        os: linux
        arch: ${{ matrix.arch }}

  build-darwin:
    runs-on: macos-latest
    strategy:
      matrix:
        working-directory:
        - exec
        - http
        arch:
        - amd64
    steps:

    - uses: actions/checkout@v2
    
    - id: Build_Plugin
      uses: ./.github/actions/build-plugin
      with:
        working-directory: ${{ matrix.working-directory }}
        os: darwin
        arch: ${{ matrix.arch }}
